# Generated by Django 4.2.19 on 2025-02-14 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="production_year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1907),
                    django.core.validators.MaxValueValidator(2025),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="tail_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
